import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { FileText, Download, ExternalLink, Search } from 'lucide-react';
import { Card, CardContent, CardHeader, Button } from '../components/ui';

const mockMarkdown = `
# Billing System Documentation

This document outlines the architecture and implementation details of the billing system, generated automatically by the DocuGen MCP Agent.

## Overview

The billing system is responsible for managing user subscriptions, processing payments via Stripe, and generating invoices. It is built around a core \`BillingService\` class that orchestrates these operations.

## Core Components

### 1. \`BillingService\` (\`src/services/billing.ts\`)

This is the primary service class. It handles the business logic for subscriptions.

**Key Methods:**
*   \`createSubscription(userId: string, planId: string)\`: Initiates a new Stripe checkout session.
*   \`cancelSubscription(subscriptionId: string)\`: Cancels an active subscription immediately.
*   \`handleWebhook(event: Stripe.Event)\`: Processes asynchronous events from Stripe (e.g., \`invoice.payment_succeeded\`).

### 2. API Endpoints (\`src/routes/api.ts\`)

The service is exposed via the following REST endpoints:

*   **POST \`/api/billing/subscribe\`**
    *   **Body:** \`{ planId: string }\`
    *   **Response:** \`{ checkoutUrl: string }\`
    *   **Auth:** Required (Bearer Token)
*   **POST \`/api/billing/cancel\`**
    *   **Body:** \`{ subscriptionId: string }\`
    *   **Response:** \`{ status: "cancelled" }\`
    *   **Auth:** Required (Bearer Token)

## Database Schema

The system relies on the \`Subscription\` model defined in \`src/models/Subscription.ts\`.

| Field | Type | Description |
| :--- | :--- | :--- |
| \`id\` | UUID | Primary Key |
| \`userId\` | UUID | Foreign key to User table |
| \`stripeCustomerId\` | String | The customer ID in Stripe |
| \`status\` | Enum | \`active\`, \`past_due\`, \`canceled\` |
| \`currentPeriodEnd\` | DateTime | When the current billing cycle ends |

## Webhook Handling

Stripe webhooks are received at \`/api/webhooks/stripe\`. The payload is verified using the \`STRIPE_WEBHOOK_SECRET\` environment variable before processing. The \`BillingService.handleWebhook\` method is responsible for updating the local database state based on these events.
`;

export function Docs() {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedDoc, setSelectedDoc] = useState('billing-system.md');

  const docsList = [
    { id: 'billing-system.md', title: 'Billing System', date: '2 hours ago', size: '2.4 KB' },
    { id: 'auth-flow.md', title: 'Authentication Flow', date: '1 day ago', size: '4.1 KB' },
    { id: 'database-schema.md', title: 'Database Schema', date: '3 days ago', size: '12.8 KB' },
  ];

  return (
    <div className="space-y-8 animate-in fade-in duration-500 h-full flex flex-col">
      <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Generated Documentation</h1>
          <p className="text-gray-400">View and export documentation generated by the MCP agent.</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" className="flex-1 sm:flex-none">
            <ExternalLink className="w-4 h-4" />
            <span className="hidden sm:inline">Open in Editor</span>
            <span className="sm:hidden">Open</span>
          </Button>
          <Button className="flex-1 sm:flex-none">
            <Download className="w-4 h-4" />
            <span className="hidden sm:inline">Export PDF</span>
            <span className="sm:hidden">Export</span>
          </Button>
        </div>
      </header>

      <div className="flex flex-col lg:flex-row gap-6 flex-1 min-h-0">
        {/* Sidebar List */}
        <Card className="w-full lg:w-80 flex flex-col shrink-0 lg:h-full max-h-[300px] lg:max-h-none">
          <div className="p-4 border-b border-white/10">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
              <input 
                type="text" 
                placeholder="Search docs..." 
                className="w-full bg-[#0a0a0a] border border-white/10 rounded-lg pl-9 pr-3 py-2 text-sm text-white focus:outline-none focus:border-[var(--color-accent)] transition-colors"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-2 space-y-1">
            {docsList.map((doc) => (
              <button
                key={doc.id}
                onClick={() => setSelectedDoc(doc.id)}
                className={`w-full text-left p-3 rounded-lg transition-colors ${
                  selectedDoc === doc.id 
                    ? 'bg-[var(--color-accent)]/10 border border-[var(--color-accent)]/20' 
                    : 'hover:bg-white/5 border border-transparent'
                }`}
              >
                <div className="flex items-center gap-3">
                  <FileText className={`w-4 h-4 ${selectedDoc === doc.id ? 'text-[var(--color-accent)]' : 'text-gray-500'}`} />
                  <div className="min-w-0 flex-1">
                    <p className={`text-sm font-medium truncate ${selectedDoc === doc.id ? 'text-white' : 'text-gray-300'}`}>
                      {doc.title}
                    </p>
                    <div className="flex items-center justify-between mt-1">
                      <p className="text-xs text-gray-500">{doc.date}</p>
                      <p className="text-xs text-gray-500 font-mono">{doc.size}</p>
                    </div>
                  </div>
                </div>
              </button>
            ))}
          </div>
        </Card>

        {/* Markdown Viewer */}
        <Card className="flex-1 flex flex-col min-w-0 bg-[#0a0a0a]">
          <CardHeader 
            title={selectedDoc} 
            subtitle="Generated by DocuGen Agent"
          />
          <CardContent className="flex-1 overflow-y-auto p-8">
            <div className="prose prose-invert prose-pre:bg-[#1a1a1a] prose-pre:border prose-pre:border-white/10 max-w-none">
              <ReactMarkdown>{mockMarkdown}</ReactMarkdown>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
